[package]
name = "powernotd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
notify-rust = "4.8.0"

[build-dependencies]
clap = { version = "4.2.1", features = ["derive"] }
clap_mangen = "0.2.10"
