.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH powernotd 1  "powernotd 1.0.0" 
.SH NAME
powernotd \- Powernotd is a battery\-level notification daemon that sends notification using the xdg desktop notification standard.
.SH SYNOPSIS
\fBpowernotd\fR [\fB\-s\fR|\fB\-\-status\-level\fR] [\fB\-c\fR|\fB\-\-charging\-state\fR] [\fB\-f\fR|\fB\-\-config\-file\fR] [\fB\-n\fR|\fB\-\-notify\-now\fR] [\fB\-t\fR|\fB\-\-list\-thresholds\fR] [\fB\-p\fR|\fB\-\-show\-config\-path\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Powernotd is a battery\-level notification daemon that sends notification using the xdg desktop notification standard.
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-status\-level\fR
Print the current battery\-level to stdout then exit
.TP
\fB\-c\fR, \fB\-\-charging\-state\fR
Print charging status \*(Aqcharging\*(Aq, \*(Aqdischarging\*(Aq, \*(Aqfull\*(Aq or \*(Aqunknown\*(Aq to stdout then exit
.TP
\fB\-f\fR, \fB\-\-config\-file\fR=\fICONFIG_FILE\fR
Set config\-file path if needed, otherwise $XDG_CONFIG_HOME/powernotd/config.json is used
.TP
\fB\-n\fR, \fB\-\-notify\-now\fR
Send desktop notification with current battery\-level then exit
.TP
\fB\-t\fR, \fB\-\-list\-thresholds\fR
List all notification thresholds in the format \*(Aqa_1%, a_2%, ..., a_n%\*(Aq that are specified in the config\-file
.TP
\fB\-p\fR, \fB\-\-show\-config\-path\fR
Display the path to the config\-file
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v1.0.0
.SH AUTHORS
laeri@laeri.me
